grpc:
  server:
    runner:
      enabled: true
  client:
    cloud-grpc-server:
      address: 'discovery:///cloud-grpc-server'
server:
  port: 8082
#指定应用名称
spring:
  application:
    name: grpc-server-demo
  cloud:
    nacos:
      discovery:
        #命名空间
        namespace: public
        #注册中心地址
        server-addr: http://127.0.0.1:8848
        username: nacos
        password: nacos
        metadata:
          gRPC_port: 50051
