grpc:
  client:
    cloud-grpc-server:
      address: 'discovery:///cloud-grpc-server'
    api:
      enabled: true
server:
  port: 8081
#指定应用名称
spring:
  application:
    name: grpc-client-demo
  cloud:
    nacos:
      discovery:
        #命名空间
        namespace: public
        #注册中心地址
        server-addr: http://127.0.0.1:8848
        username: nacos
        password: nacos
        enabled: true
